### ISSUE TITLE
RSS/Atom feed 

### ISSUE THREAD

**Issue by xuhcc** [vbuterin/blog#8]
Please add [RSS](https://en.wikipedia.org/wiki/RSS) or [Atom](https://en.wikipedia.org/wiki/Atom_(Web_standard)) feed to the blog. It allows readers to automatically check for new articles.

**Comment by vbuterin** [comment]
Ok, I am looking into how to do this now. Can someone confirm for me my current understanding? See below.

I need to make an XML file, which lives at the URL http://vitalik.ca/feed/, which has the following format:

```
<?xml version="1.0" ?>
<rss version="2.0">
<channel>
  <title>Vitalik Buterin's blog</title>
  <link>https://vitalik.ca</link>
  <description>Vitalik Buterin's blog</description>
  <image>
      <url>https://vitalik.ca/images/icon.png</url>
  </image>
  <item>
      <title>Convex and Concave Dispositions</title>
      <link>https://vitalik.ca/general/2020/11/08/concave.html</link>
      <description></description>
  </item>
  <item>
      <title>Why Proof of Stake (Nov 2020)</title>
      <link>https://vitalik.ca/general/2020/11/06/pos2020.html</link>
      <description></description>
    </item>
</channel>
</rss> 
```

I also need to add the following to the head of the html file on http://vitalik.ca itself (and every article too?):
```
<link rel="alternate" type="application/rss+xml" href="https://vitalik.ca/feed/" title="Vitalik Buterin's blog">
```

**Comment by rafasashi** [comment]
Yes it looks good. 

You could perhaps specify the encoding in the first markup:

`<?xml version="1.0" encoding="utf-8"?>`

And add the publication date because some readers will need it to manage the feed:

`<pubDate>Tue, 15 Nov 1854 11:09:11 -0400</pubDate>`

The MIME type of the auto discovery link is ok as well. You coud consider implementing a PubSubHubbub push link and/or test your feed against [https://pubsubhubbub.appspot.com/publish](https://pubsubhubbub.appspot.com/publish)

**Comment by xuhcc** [comment]
@vbuterin The [validator service](https://validator.w3.org/feed/) shows several warnings for this RSS feed. But I think feedreaders tend to be very forgiving when it comes to parsing so it's safe to ignore these warnings.

>I also need to add the following to the head of the html file on http://vitalik.ca itself (and every article too?):

Yes, ideally it should be present on every page so people can subscribe to it right away. For example I use browser extension that automatically detects rss/atom feeds on web pages and shows "subscribe" button in address bar if the feed is present.

**Comment by rafasashi** [comment]
Indeed, to get the validation you need to add a <title> and <link> to the image.

This will do:

```
<?xml version="1.0" ?>
<rss version="2.0"
	xmlns:atom="http://www.w3.org/2005/Atom"
>
<channel>
  <title>Vitalik Buterin's blog</title>
<atom:link href="https://vitalik.ca/feed/" rel="self" type="application/rss+xml" />
  <link>https://vitalik.ca</link>
  <description>Vitalik Buterin's blog</description>
  <image>
		<title>Vitalik Buterin's blog</title>
		<url>https://vitalik.ca/images/icon.png</url>
		<link>https://vitalik.ca</link>
  </image>
  <item>
      <title>Convex and Concave Dispositions</title>
      <link>https://vitalik.ca/general/2020/11/08/concave.html</link>
      <description></description>
  </item>
  <item>
      <title>Why Proof of Stake (Nov 2020)</title>
      <link>https://vitalik.ca/general/2020/11/06/pos2020.html</link>
      <description></description>
    </item>
</channel>
</rss> 
```

**Comment by abadmian** [comment]
Getting a 404 for the feed. Would be very useful to have an RSS link for when there’s new content.

**Comment by safak-oezesenlik** [comment]
Please add the feed. I love your posts

**Comment by xuhcc** [comment]
As a temporary workaround, [Nitter](https://nitter.net/about) (an alternative Twitter front-end) can be used to get Vitalik's twitter feed in RSS format: https://nitter.net/VitalikButerin/search/rss?f=tweets&e-replies=on. Links to blog posts usually appear there.

**Comment by safak-oezesenlik** [comment]
Yeah but a RSS feed contains usually the full text.

I hope and think that adding a feed is easy compaded to ther other stuff you do

**Comment by xuhcc** [comment]
https://vitalik.ca/feed.xml (added in a5751eb279446c864448ce7927c4f5db413536b9)

**Comment by prisonblues** [comment]
@vbuterin - can you update your feed links from vitalik.ca to vitalik eth.limo please? I can do a custom re-write rule, but would be better if you fix the links.

**Comment by hhamud** [comment]
Here's a temporary work around since I set up a cron job that scrapes his site and creates an rss feed. https://www.hamzahamud.com/feed/
