### ISSUE TITLE
Wrong article displayed in some categories

### ISSUE THREAD

**Issue by rafasashi** [vbuterin/blog#9]
I think that some categories like 中文, Italiano or Français are pointing to the wrong articles if not empty:

https://github.com/vbuterin/blog/blob/4052117b18fe0a108714fa254676b3e6a88dd377/site/categories/fran%C3%A7ais.html#L70

**Comment by vbuterin** [comment]
Wow, thanks a lot for this! Just fixed it in the blogmaker script.
