### ISSUE TITLE
Clarification: `s/0.5/0.3` in the `Exit games for EVM validiums: the return of Plasma` post?

### ISSUE THREAD

**Issue by Olshansk** [vbuterin/blog#91]
Is this a typo or intentional in https://vitalik.eth.limo/general/2023/11/14/neoplasma.html?

![evmutxo](https://github.com/vbuterin/blog/assets/1892194/2432fde3-7039-4b32-a316-84812ae8bb60)

Also, our team is very big on the [text-to-diagram](https://text-to-diagram.com/) paradigm, so I highly recommend you check it out if it's not something you've ever been exposed to. Makes maintaining / updating / extending them (especially when it comes to open source) much easier.

I started it for this image as an example:

```mermaid
graph TD
    A["0.3 ETH <br> (Alice)"] -- 0.3 --> D["1.1 ETH <br> (David)"]
    B["0.5 ETH <br> (Bob)"] -- 0.5 --> D["1.1 ETH <br> (David)"]
    C["0.3 ETH <br> (Charlie)"] -- 0.3 --> D["1.1 ETH <br> (David)"]
    D -- 0.9 --> E["0.9ETH <br> (David)"]
    D -- 0.2 --> D2["0.2 ETH <br> (Eve)"]    
```

**Comment by vbuterin** [comment]
fixed!
